USE ESSEDB;

ALTER TABLE TB_USUARIO 
    DROP FOREIGN KEY FK_TB_USUARIO_ID_ENDERECO;

ALTER TABLE TB_ADMINISTRADOR 
    DROP FOREIGN KEY FK_TB_ADMINISTRADOR_ID_USUARIO;

ALTER TABLE TB_ALUNO 
    DROP FOREIGN KEY FK_TB_ALUNO_ID_USUARIO;

ALTER TABLE TB_CURSO 
    DROP FOREIGN KEY FK_TB_CURSO_ID_INSTITUICAO;

ALTER TABLE TB_DISCIPLINA 
    DROP FOREIGN KEY FK_TB_DISCIPLINA_ID_CURSO;

ALTER TABLE TB_DISCIPLINA 
    DROP FOREIGN KEY FK_TB_DISCIPLINA_ID_SALA_CHAT;

ALTER TABLE TB_DISCIPLINA 
    DROP FOREIGN KEY FK_TB_DISCIPLINA_ID_PROFESSOR;

ALTER TABLE TB_EMAIL 
    DROP FOREIGN KEY FK_TB_EMAIL_ID_USUARIO;

ALTER TABLE TB_EMAIL 
    DROP FOREIGN KEY FK_TB_EMAIL_ID_INSTITUICAO;

ALTER TABLE TB_FONE 
    DROP FOREIGN KEY FK_TB_FONE_ID_INSTITUICAO;

ALTER TABLE TB_FONE 
    DROP FOREIGN KEY FK_TB_FONE_ID_USUARIO;

ALTER TABLE TB_INSTITUICAO 
    DROP FOREIGN KEY FK_TB_INSTITUICAO_ID_ENDERECO;

ALTER TABLE TB_PROFESSOR 
    DROP FOREIGN KEY FK_TB_PROFESSOR_ID_USUARIO;

ALTER TABLE TB_DISCIPLINA_ALUNO 
    DROP FOREIGN KEY FK_TB_DISCIPLINA_ALUNO_ID_DISCIPLINA;

ALTER TABLE TB_DISCIPLINA_ALUNO 
    DROP FOREIGN KEY FK_TB_DISCIPLINA_ALUNO_ID_ALUNO;

ALTER TABLE TB_DISCIPLINA_MONITOR 
    DROP FOREIGN KEY FK_TB_DISCIPLINA_MONITOR_ID_DISCIPLINA;

ALTER TABLE TB_DISCIPLINA_MONITOR 
    DROP FOREIGN KEY FK_TB_DISCIPLINA_MONITOR_ID_ALUNO;
 
ALTER TABLE TB_USUARIO_GRUPO 
    DROP FOREIGN KEY FK_TB_USUARIO_GRUPO_ID_USUARIO;

ALTER TABLE TB_USUARIO_GRUPO 
    DROP FOREIGN KEY FK_TB_USUARIO_GRUPO_ID_GRUPO;

DROP TABLE IF EXISTS TB_USUARIO;
DROP TABLE IF EXISTS TB_ADMINISTRADOR;
DROP TABLE IF EXISTS TB_ALUNO;
DROP TABLE IF EXISTS TB_CURSO;
DROP TABLE IF EXISTS TB_DISCIPLINA;
DROP TABLE IF EXISTS TB_EMAIL;
DROP TABLE IF EXISTS TB_ENDERECO;
DROP TABLE IF EXISTS TB_FONE;
DROP TABLE IF EXISTS TB_INSTITUICAO;
DROP TABLE IF EXISTS TB_PROFESSOR;
DROP TABLE IF EXISTS TB_GRUPO;
DROP TABLE IF EXISTS TB_SALA_DE_CHAT;
DROP TABLE IF EXISTS TB_DISCIPLINA_ALUNO;
DROP TABLE IF EXISTS TB_DISCIPLINA_MONITOR;
DROP TABLE IF EXISTS TB_USUARIO_GRUPO;

CREATE TABLE TB_USUARIO (
    ID BIGINT AUTO_INCREMENT NOT NULL, 
    TXT_APELIDO VARCHAR(10), 
    TXT_CPF VARCHAR(14), 
    DT_NASCIMENTO DATE, 
    TXT_NOME VARCHAR(30), 
    TXT_SOBRENOME VARCHAR(30),
    TXT_SENHA VARCHAR(255), 
    TXT_SAL VARCHAR(45), 
    TXT_SEXO VARCHAR(1),
    TXT_EMAIL VARCHAR(150),
    ID_ENDERECO BIGINT, 
    PRIMARY KEY (ID)
);

CREATE TABLE TB_ADMINISTRADOR (
    ID_USUARIO BIGINT NOT NULL,    
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE TB_ALUNO (
    ID_USUARIO BIGINT NOT NULL, 
    TXT_MATRICULA VARCHAR(20), 
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE TB_CURSO (
    ID BIGINT AUTO_INCREMENT NOT NULL, 
    TXT_NOME VARCHAR(255), 
    ID_INSTITUICAO BIGINT, 
    PRIMARY KEY (ID)
);

CREATE TABLE TB_DISCIPLINA (
    ID BIGINT AUTO_INCREMENT NOT NULL, 
    TXT_NOME VARCHAR(255), 
    ID_CURSO BIGINT, 
    ID_PROFESSOR BIGINT, 
    ID_SALA_CHAT BIGINT, 
    PRIMARY KEY (ID)
);

CREATE TABLE TB_EMAIL (
    ID BIGINT AUTO_INCREMENT NOT NULL, 
    TXT_EMAIL VARCHAR(150), 
    ID_INSTITUICAO BIGINT, 
    ID_USUARIO BIGINT, 
    PRIMARY KEY (ID)
);

CREATE TABLE TB_ENDERECO (
    ID BIGINT AUTO_INCREMENT NOT NULL, 
    TXT_LOGRADOURO VARCHAR(255), 
    TXT_NUMERO VARCHAR(5), 
    TXT_COMPLEMENTO VARCHAR(150), 
    TXT_CEP VARCHAR(9), 
    TXT_BAIRRO VARCHAR(150), 
    TXT_CIDADE VARCHAR(150), 
    TXT_ESTADO VARCHAR(2),     
    PRIMARY KEY (ID)
);

CREATE TABLE TB_FONE (
    ID BIGINT AUTO_INCREMENT NOT NULL, 
    TXT_FONE VARCHAR(14), 
    ID_INSTITUICAO BIGINT, 
    ID_USUARIO BIGINT, 
    PRIMARY KEY (ID)
);

CREATE TABLE TB_INSTITUICAO (
    ID BIGINT AUTO_INCREMENT NOT NULL, 
    TXT_NOME VARCHAR(255), 
    TXT_SIGLA VARCHAR(10), 
    TXT_CNPJ VARCHAR(18), 
    ID_ENDERECO BIGINT, 
    PRIMARY KEY (ID)
);

CREATE TABLE TB_PROFESSOR (
    ID_USUARIO BIGINT NOT NULL, 
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE TB_SALA_DE_CHAT (
    ID BIGINT AUTO_INCREMENT NOT NULL, 
    TXT_DESCRICAO VARCHAR(255), 
    PRIMARY KEY (ID)
);

CREATE TABLE TB_GRUPO (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    TXT_NOME VARCHAR(45), 
    PRIMARY KEY (ID)
);

CREATE TABLE TB_DISCIPLINA_ALUNO (
    ID_ALUNO BIGINT NOT NULL, 
    ID_DISCIPLINA BIGINT NOT NULL, 
    PRIMARY KEY (ID_ALUNO, ID_DISCIPLINA)
);

CREATE TABLE TB_DISCIPLINA_MONITOR (
    ID_DISCIPLINA BIGINT NOT NULL, 
    ID_ALUNO BIGINT NOT NULL, 
    PRIMARY KEY (ID_DISCIPLINA, ID_ALUNO)
);

CREATE TABLE TB_USUARIO_GRUPO (
    ID_USUARIO BIGINT NOT NULL, 
    ID_GRUPO BIGINT NOT NULL, 
    PRIMARY KEY (ID_USUARIO, ID_GRUPO)
);

ALTER TABLE TB_USUARIO 
    ADD CONSTRAINT FK_TB_USUARIO_ID_ENDERECO 
    FOREIGN KEY (ID_ENDERECO) 
    REFERENCES TB_ENDERECO (ID);

ALTER TABLE TB_USUARIO
    ADD CONSTRAINT UK_CPF 
    UNIQUE (TXT_CPF);

ALTER TABLE TB_ADMINISTRADOR 
    ADD CONSTRAINT FK_TB_ADMINISTRADOR_ID_USUARIO  
    FOREIGN KEY (ID_USUARIO) 
    REFERENCES TB_USUARIO (ID);

ALTER TABLE TB_ALUNO 
    ADD CONSTRAINT FK_TB_ALUNO_ID_USUARIO 
    FOREIGN KEY (ID_USUARIO) 
    REFERENCES TB_USUARIO (ID);

ALTER TABLE TB_CURSO 
    ADD CONSTRAINT FK_TB_CURSO_ID_INSTITUICAO 
    FOREIGN KEY (ID_INSTITUICAO) 
    REFERENCES TB_INSTITUICAO (ID);

ALTER TABLE TB_DISCIPLINA 
    ADD CONSTRAINT FK_TB_DISCIPLINA_ID_CURSO 
    FOREIGN KEY (ID_CURSO) 
    REFERENCES TB_CURSO (ID);

ALTER TABLE TB_DISCIPLINA 
    ADD CONSTRAINT FK_TB_DISCIPLINA_ID_SALA_CHAT 
    FOREIGN KEY (ID_SALA_CHAT) 
    REFERENCES TB_SALA_DE_CHAT (ID);

ALTER TABLE TB_DISCIPLINA 
    ADD CONSTRAINT FK_TB_DISCIPLINA_ID_PROFESSOR 
    FOREIGN KEY (ID_PROFESSOR) 
    REFERENCES TB_USUARIO (ID);

ALTER TABLE TB_EMAIL 
    ADD CONSTRAINT FK_TB_EMAIL_ID_USUARIO 
    FOREIGN KEY (ID_USUARIO) 
    REFERENCES TB_USUARIO (ID);

ALTER TABLE TB_EMAIL 
    ADD CONSTRAINT FK_TB_EMAIL_ID_INSTITUICAO 
    FOREIGN KEY (ID_INSTITUICAO) 
    REFERENCES TB_INSTITUICAO (ID);

ALTER TABLE TB_FONE 
    ADD CONSTRAINT FK_TB_FONE_ID_INSTITUICAO 
    FOREIGN KEY (ID_INSTITUICAO) 
    REFERENCES TB_INSTITUICAO (ID);

ALTER TABLE TB_FONE 
    ADD CONSTRAINT FK_TB_FONE_ID_USUARIO 
    FOREIGN KEY (ID_USUARIO) 
    REFERENCES TB_USUARIO (ID);

ALTER TABLE TB_INSTITUICAO 
    ADD CONSTRAINT FK_TB_INSTITUICAO_ID_ENDERECO 
    FOREIGN KEY (ID_ENDERECO) 
    REFERENCES TB_ENDERECO (ID);

ALTER TABLE TB_PROFESSOR 
    ADD CONSTRAINT FK_TB_PROFESSOR_ID_USUARIO 
    FOREIGN KEY (ID_USUARIO) 
    REFERENCES TB_USUARIO (ID);

ALTER TABLE TB_DISCIPLINA_ALUNO 
    ADD CONSTRAINT FK_TB_DISCIPLINA_ALUNO_ID_DISCIPLINA 
    FOREIGN KEY (ID_DISCIPLINA) 
    REFERENCES TB_DISCIPLINA (ID);

ALTER TABLE TB_DISCIPLINA_ALUNO 
    ADD CONSTRAINT FK_TB_DISCIPLINA_ALUNO_ID_ALUNO 
    FOREIGN KEY (ID_ALUNO) 
    REFERENCES TB_USUARIO (ID);

ALTER TABLE TB_DISCIPLINA_MONITOR 
    ADD CONSTRAINT FK_TB_DISCIPLINA_MONITOR_ID_DISCIPLINA 
    FOREIGN KEY (ID_DISCIPLINA) 
    REFERENCES TB_DISCIPLINA (ID);

ALTER TABLE TB_DISCIPLINA_MONITOR 
    ADD CONSTRAINT FK_TB_DISCIPLINA_MONITOR_ID_ALUNO 
    FOREIGN KEY (ID_ALUNO) 
    REFERENCES TB_USUARIO (ID);

ALTER TABLE TB_USUARIO_GRUPO 
    ADD CONSTRAINT FK_TB_USUARIO_GRUPO_ID_USUARIO 
    FOREIGN KEY (ID_USUARIO) 
    REFERENCES TB_USUARIO (ID);

ALTER TABLE TB_USUARIO_GRUPO 
    ADD CONSTRAINT FK_TB_USUARIO_GRUPO_ID_GRUPO
    FOREIGN KEY (ID_GRUPO) 
    REFERENCES TB_GRUPO (ID);

